name: ♻️ Generate Metadata ♻️
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
  # - cron: "0 3 * * *"  #UTC 03:00 AM --> 08:45 AM NPT @everyday
  # - cron: "0 */3 * * *" #every 3 hrs
   - cron: "0 0/1,3,4,6,7,9,10,12,13,15,16,18,19,21,22 * * *" #every 90 mins
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 200
    permissions:
      attestations: write   
      contents: write
      id-token: write
      issues: write
      packages: write
      statuses: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: "bincache"
            script: "${GITHUB_WORKSPACE}/main/bincache/scripts/gen_meta_aarch64-Linux.sh"
            arch: "aarch64"
            file: "/tmp/bincache_aarch64-Linux.json"

          - repo: "bincache"
            script: "${GITHUB_WORKSPACE}/main/bincache/scripts/gen_meta_x86_64-Linux.sh"
            arch: "x86_64"
            file: "/tmp/bincache_x86_64-Linux.json"

          - repo: "pkgcache"
            script: "${GITHUB_WORKSPACE}/main/pkgcache/scripts/gen_meta_aarch64-Linux.sh"
            arch: "aarch64"
            file: "/tmp/pkgcache_aarch64-Linux.json"

          - repo: "pkgcache"
            script: "${GITHUB_WORKSPACE}/main/pkgcache/scripts/gen_meta_x86_64-Linux.sh"
            arch: "x86_64"
            file: "/tmp/pkgcache_x86_64-Linux.json"

          - repo: "soarpkgs"
            #script: "${GITHUB_WORKSPACE}/main/soarpkgs/scripts/gen_meta.sh"
            script: "${GITHUB_WORKSPACE}/main/soarpkgs/scripts/gen_meta_docker.sh"
            arch: "MULTI"
            file: "/tmp/INDEX.json"

          - repo: "soarpkgs"
            script: "${GITHUB_WORKSPACE}/main/soarpkgs/scripts/gen_ghcr_backage.sh"
            arch: "MULTI"
            file: "/tmp/BACKAGE.json"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main
          fetch-depth: "1"
          filter: "blob:none"

      - name: Install Addons
        run: |
          #presets
          set +x ; set +e
          #-------------#
          bash <(curl -qfsSL "https://raw.githubusercontent.com/pkgforge/devscripts/refs/heads/main/Linux/install_bins_curl.sh")
        continue-on-error: true

      - name: Setup Env
        run: |
          #presets
          set +x ; set +e
          #-------------#
          #tmp
          SYSTMP="$(dirname $(mktemp -u))" && export SYSTMP="${SYSTMP}"
          echo "SYSTMP=${SYSTMP}" >> "${GITHUB_ENV}"
          #-------------#
          #GH Dirs
          mkdir -pv "${GITHUB_WORKSPACE}/main/bincache/data"
          mkdir -pv "${GITHUB_WORKSPACE}/main/misc/data"
          mkdir -pv "${GITHUB_WORKSPACE}/main/pkgcache/data"
          mkdir -pv "${GITHUB_WORKSPACE}/main/soarpkgs/data"
          #-------------#
          ##rclone
          echo "${{ secrets.CF_META }}" > "${HOME}/.rclone.conf"
          #-------------#
          ##User-Agent
          USER_AGENT="$(curl -qfsSL 'https://pub.ajam.dev/repos/Azathothas/Wordlists/Misc/User-Agents/ua_chrome_macos_latest.txt')" && export USER_AGENT="${USER_AGENT}"
          echo "USER_AGENT=${USER_AGENT}" >> "${GITHUB_ENV}"
        continue-on-error: true

      - name: Generate (${{ matrix.repo }}/${{ matrix.arch }})
        env:
          #GITHUB_TOKEN: "${{ github.token }}"
          GITHUB_TOKEN: "${{ secrets.RO_GHTOKEN }}"
        run: |
          #presets
          set +x ; set +e
          #-------------#
          dos2unix --quiet "${{ matrix.script }}"
          chmod +x "${{ matrix.script }}"
          #PARALLEL_LIMIT="50" bash "${{ matrix.script }}"
          PARALLEL_LIMIT="$(($(nproc)+1))" bash "${{ matrix.script }}"
        continue-on-error: true

      - name: Get DateTime & Purge files (=> 95 MB)
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          UTC_TIME="$(TZ='UTC' date +'%Y-%m-%d (%I:%M:%S %p)')"
          echo "UTC_TIME=${UTC_TIME}" >> "${GITHUB_ENV}"
          #Sync
          cd "${GITHUB_WORKSPACE}/main"
          git pull origin main --no-edit 2>/dev/null
          #Purge
          find "${GITHUB_WORKSPACE}/main" -path "${GITHUB_WORKSPACE}/main/.git" -prune -o -type f -size +95M -exec rm -rvf "{}" + 2>/dev/null
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./main
          commit_user_name: Azathothas
          commit_user_email: AjamX101@gmail.com
          commit_message: "✅ Updated Metadata [${{ matrix.repo }}-${{ matrix.arch }}] ♻️"
          #push_options: '--force'
        continue-on-error: true

      - name: Pull & Push (2)
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          cd "${GITHUB_WORKSPACE}/main"
          git pull origin main --no-edit 2>/dev/null
          git pull origin main --ff-only ; git merge --no-ff -m "Merge & Sync"
        continue-on-error: true   
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./main
          commit_user_name: Azathothas
          commit_user_email: AjamX101@gmail.com
          commit_message: "✅ Updated Metadata [${{ matrix.repo }}-${{ matrix.arch }}] ♻️"
          #push_options: '--force'
        continue-on-error: true

      - name: Report Invalid SBUILDS
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          ##Failed SBUILDS (Binaries)
          if [[ -s "${SYSTMP}/INVALID_BINARIES.txt" && $(wc -l < "${SYSTMP}/INVALID_BINARIES.txt" | tr -d '[:space:]') -gt 1 ]]; then
           #sed 's|.*/binaries|https://github.com/pkgforge/soarpkgs/blob/main/binaries|' -i  "${SYSTMP}/INVALID_BINARIES.txt"
           #sed 's|^|- |' -i "${SYSTMP}/INVALID_BINARIES.txt"
           #sort -u "${SYSTMP}/INVALID_BINARIES.txt" -o "${SYSTMP}/INVALID_BINARIES.txt"
           export HAS_INVALID_BINS="TRUE"
           echo "HAS_INVALID_BINS=${HAS_INVALID_BINS}" >> "${GITHUB_ENV}"
          fi
          ##Failed SBUILDS (Packages)
          if [[ -s "${SYSTMP}/INVALID_PACKAGES.txt" && $(wc -l < "${SYSTMP}/INVALID_PACKAGES.txt" | tr -d '[:space:]') -gt 1 ]]; then
           #sed 's|.*/packages|https://github.com/pkgforge/soarpkgs/blob/main/packages|' -i  "${SYSTMP}/INVALID_PACKAGES.txt"
           #sed 's|^|- |' -i "${SYSTMP}/INVALID_PACKAGES.txt"
           #sort -u "${SYSTMP}/INVALID_PACKAGES.txt" -o "${SYSTMP}/INVALID_PACKAGES.txt"
           export HAS_INVALID_PKGS="TRUE"
           echo "HAS_INVALID_PKGS=${HAS_INVALID_PKGS}" >> "${GITHUB_ENV}"
          fi
        continue-on-error: true

      - name: Create Issue (Invalid Binary SBUILDS)
        if: env.HAS_INVALID_BINS == 'TRUE'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: SBUILDS (Failed Binary Validation)
          content-filepath: "/tmp/INVALID_BINARIES.txt"
          labels: report, automated issue
        continue-on-error: true

      - name: Create Issue (Invalid Package SBUILDS)
        if: env.HAS_INVALID_PKGS == 'TRUE'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: SBUILDS (Failed Package Validation)
          content-filepath: "/tmp/INVALID_PACKAGES.txt"
          labels: report, automated issue
        continue-on-error: true

      - name: Report Duplicate pkg_webpages
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          if [[ -s "${SYSTMP}/DUPES_PKG_WEBPAGE.json" && $(wc -l < "${SYSTMP}/DUPES_PKG_WEBPAGE.json" | tr -d '[:space:]') -gt 1 ]]; then
           echo '```json' > "${SYSTMP}/DUPES_PKG_WEBPAGE.txt"
           cat "${SYSTMP}/DUPES_PKG_WEBPAGE.json" >> "${SYSTMP}/DUPES_PKG_WEBPAGE.txt"
           echo '```' >> "${SYSTMP}/DUPES_PKG_WEBPAGE.txt"
           export HAS_DUPE_PKG_WEBPAGES="TRUE"
           echo "HAS_DUPE_PKG_WEBPAGES=${HAS_DUPE_PKG_WEBPAGES}" >> "${GITHUB_ENV}"
          fi
        continue-on-error: true

      - name: Create Issue (Duplicate Webpages)
        if: env.HAS_DUPE_PKG_WEBPAGES == 'TRUE'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: SBUILDS (Duplicate Webpages)
          content-filepath: "/tmp/DUPES_PKG_WEBPAGE.txt"
          labels: report, automated issue
        continue-on-error: true

      - name: Report Missing pkg_id
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          if [[ -s "${SYSTMP}/MISSING_PKG_ID.json" && $(wc -l < "${SYSTMP}/MISSING_PKG_ID.json" | tr -d '[:space:]') -gt 1 ]]; then
           echo '```json' > "${SYSTMP}/MISSING_PKG_ID.txt"
           cat "${SYSTMP}/MISSING_PKG_ID.json" >> "${SYSTMP}/MISSING_PKG_ID.txt"
           echo '```' >> "${SYSTMP}/MISSING_PKG_ID.txt"
           export HAS_MISSING_PKG_ID="TRUE"
           echo "HAS_MISSING_PKG_ID=${HAS_MISSING_PKG_ID}" >> "${GITHUB_ENV}"
          fi
        continue-on-error: true

      - name: Create Issue (Missing Package ID)
        if: env.HAS_MISSING_PKG_ID == 'TRUE'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: SBUILDS (Missing Package ID)
          content-filepath: "/tmp/MISSING_PKG_ID.txt"
          labels: report, automated issue
        continue-on-error: true

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v2.2.0
        with:
          subject-name: "metadata-${{ matrix.repo }}-${{ matrix.arch }}"
          subject-path: "${{ matrix.file }}"
          show-summary: true
        continue-on-error: true

  moderate:
    needs: [generate]
    runs-on: ubuntu-latest
    timeout-minutes: 200
    permissions:
      attestations: write   
      contents: write
      id-token: write
      issues: write
      packages: write
      statuses: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main
          filter: "blob:none"

      - name: Install Addons
        run: |
          #presets
          set +x ; set +e
          #-------------#
          #tmp
          SYSTMP="$(dirname $(mktemp -u))" && export SYSTMP="${SYSTMP}"
          echo "SYSTMP=${SYSTMP}" >> "${GITHUB_ENV}"
          #bash <(curl -qfsSL "https://raw.githubusercontent.com/pkgforge/devscripts/refs/heads/main/Linux/install_bins_curl.sh")
          ##CoreUtils
          sudo apt update -y
          sudo apt install bc coreutils curl dos2unix fdupes jq moreutils wget -y
          sudo apt-get install apt-transport-https apt-utils ca-certificates coreutils dos2unix gnupg2 jq moreutils p7zip-full rename rsync software-properties-common texinfo tmux util-linux wget -y 2>/dev/null ; sudo apt-get update -y 2>/dev/null
        continue-on-error: true

      - name: Report Duplicate pkg_ids
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          curl -qfsSL "https://meta.pkgforge.dev/bincache/aarch64-Linux.json" | jq -r '.[] | "\(.pkg_id) --> \(.pkg_name)"' | sort | uniq -d > "${SYSTMP}/DUPES_PKG_ID.txt.tmp"
          curl -qfsSL "https://meta.pkgforge.dev/bincache/x86_64-Linux.json" | jq -r '.[] | "\(.pkg_id) --> \(.pkg_name)"' | sort | uniq -d >> "${SYSTMP}/DUPES_PKG_ID.txt.tmp"
          curl -qfsSL "https://meta.pkgforge.dev/pkgcache/aarch64-Linux.json" | jq -r '.[] | "\(.pkg_id) --> \(.pkg_name)"' | sort | uniq -d >> "${SYSTMP}/DUPES_PKG_ID.txt.tmp"
          curl -qfsSL "https://meta.pkgforge.dev/pkgcache/x86_64-Linux.json" | jq -r '.[] | "\(.pkg_id) --> \(.pkg_name)"' | sort | uniq -d >> "${SYSTMP}/DUPES_PKG_ID.txt.tmp"
          curl -qfsSL "https://meta.pkgforge.dev/soarpkgs/INDEX.json" | jq -r '.[] | "\(.pkg_id) --> \(.pkg)"' | sort | uniq -d >> "${SYSTMP}/DUPES_PKG_ID.txt.tmp"
          if [[ -s "${SYSTMP}/DUPES_PKG_ID.txt.tmp" && $(stat -c%s "${SYSTMP}/DUPES_PKG_ID.txt.tmp") -gt 3 ]]; then
           echo '```bash' > "${SYSTMP}/DUPES_PKG_ID.txt"
           cat "${SYSTMP}/DUPES_PKG_ID.txt.tmp" >> "${SYSTMP}/DUPES_PKG_ID.txt"
           echo '```' >> "${SYSTMP}/DUPES_PKG_ID.txt"
           export HAS_DUPE_PKG_IDS="TRUE"
           echo "HAS_DUPE_PKG_IDS=${HAS_DUPE_PKG_IDS}" >> "${GITHUB_ENV}"
          fi
        continue-on-error: true

      - name: Create Issue (Duplicate PKG_ID)
        if: env.HAS_DUPE_PKG_IDS == 'TRUE'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: SBUILDS (Duplicate PKG_ID)
          content-filepath: "/tmp/DUPES_PKG_ID.txt"
          labels: report, automated issue
        continue-on-error: true

      - name: Generate Diffs (BinCache)
        run: |
          #presets
          set +x ; set +e
          #-------------#
          ##Version Diff (aarch64-Linux)
          curl -qfsSL "https://meta.pkgforge.dev/soarpkgs/INDEX.json" | \
          jq --slurpfile aarch64 <(curl -qfsSL "https://meta.pkgforge.dev/bincache/aarch64-Linux.json") \
          '.[] | 
          select((.pkg_type == "static" and (.host | contains(["aarch64-linux"]))) and (
            .pkg_id as $id | 
            .version as $ver |
            ($aarch64[0] | map(.pkg_id) | contains([$id]) | not) or
            ($aarch64[0][] | select(.pkg_id == $id).version) as $aarch64_ver |
            $aarch64_ver == null or $ver != $aarch64_ver
           ))' | jq -s 'unique_by(.pkg_id) | sort_by(.pkg)' > "${GITHUB_WORKSPACE}/main/soarpkgs/data/DIFF_bincache_aarch64-Linux.json"
          ##Version Diff (x86_64-Linux)
          curl -qfsSL "https://meta.pkgforge.dev/soarpkgs/INDEX.json" | \
          jq --slurpfile x86_64 <(curl -qfsSL "https://meta.pkgforge.dev/bincache/x86_64-Linux.json") \
          '.[] | 
          select((.pkg_type == "static" and (.host | contains(["x86_64-linux"]))) and (
            .pkg_id as $id | 
            .version as $ver |
            ($x86_64[0] | map(.pkg_id) | contains([$id]) | not) or
            ($x86_64[0][] | select(.pkg_id == $id).version) as $x86_ver |
            $x86_ver == null or $ver != $x86_ver
          ))' | jq -s 'unique_by(.pkg_id) | sort_by(.pkg)' > "${GITHUB_WORKSPACE}/main/soarpkgs/data/DIFF_bincache_x86_64-Linux.json"
        continue-on-error: true

      - name: Generate Diffs (PkgCache)
        run: |
          #presets
          set +x ; set +e
          #-------------#
          ##Version Diff (aarch64-Linux)
          curl -qfsSL "https://meta.pkgforge.dev/soarpkgs/INDEX.json" | \
          jq --slurpfile aarch64 <(curl -qfsSL "https://meta.pkgforge.dev/pkgcache/aarch64-Linux.json") \
          '.[] | 
          select((.pkg_type | test("^(appbundle|appimage|archive|flatimage|gameimage|nixappimage|runimage)$"; "i")) and (.host | contains(["aarch64-linux"])) and (
            .pkg_id as $id | 
            .version as $ver |
            ($aarch64[0] | map(.pkg_id) | contains([$id]) | not) or
            ($aarch64[0][] | select(.pkg_id == $id).version) as $aarch64_ver |
            $aarch64_ver == null or $ver != $aarch64_ver
           ))' | jq -s 'unique_by(.pkg_id) | sort_by(.pkg)' > "${GITHUB_WORKSPACE}/main/soarpkgs/data/DIFF_pkgcache_aarch64-Linux.json"
          ##Version Diff (x86_64-Linux)
          curl -qfsSL "https://meta.pkgforge.dev/soarpkgs/INDEX.json" | \
          jq --slurpfile x86_64 <(curl -qfsSL "https://meta.pkgforge.dev/pkgcache/x86_64-Linux.json") \
          '.[] | 
          select((.pkg_type | test("^(appbundle|appimage|archive|flatimage|gameimage|nixappimage|runimage)$"; "i")) and (.host | contains(["x86_64-linux"])) and (
            .pkg_id as $id | 
            .version as $ver |
            ($x86_64[0] | map(.pkg_id) | contains([$id]) | not) or
            ($x86_64[0][] | select(.pkg_id == $id).version) as $x86_ver |
            $x86_ver == null or $ver != $x86_ver
          ))' | jq -s 'unique_by(.pkg_id) | sort_by(.pkg)' > "${GITHUB_WORKSPACE}/main/soarpkgs/data/DIFF_pkgcache_x86_64-Linux.json"
        continue-on-error: true

      - name: Get DateTime & Purge files (=> 95 MB)
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          UTC_TIME="$(TZ='UTC' date +'%Y-%m-%d (%I:%M:%S %p)')"
          echo "UTC_TIME=${UTC_TIME}" >> "${GITHUB_ENV}"
          #Sync
          cd "${GITHUB_WORKSPACE}/main"
          git pull origin main --no-edit 2>/dev/null
          #Purge
          find "${GITHUB_WORKSPACE}/main" -path "${GITHUB_WORKSPACE}/main/.git" -prune -o -type f -size +95M -exec rm -rvf "{}" + 2>/dev/null
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./main
          commit_user_name: Azathothas
          commit_user_email: AjamX101@gmail.com
          commit_message: "✅ Updated Metadata [Diff] ♻️"
          #push_options: '--force'
        continue-on-error: true

      - name: Pull & Push (2)
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          cd "${GITHUB_WORKSPACE}/main"
          git pull origin main --no-edit 2>/dev/null
          git pull origin main --ff-only ; git merge --no-ff -m "Merge & Sync"
        continue-on-error: true   
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./main
          commit_user_name: Azathothas
          commit_user_email: AjamX101@gmail.com
          commit_message: "✅ Updated Metadata [Diff] ♻️"
          #push_options: '--force'
        continue-on-error: true