name: ♻️↕️ Sync R2 Mirror ↕️♻️
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  #schedule:
  # - cron: "0 2 * * Sun" #UTC 02:00 AM --> 07:45 AM NPT Sun
  # - cron: "0 2 * * Wed" #UTC 02:00 AM --> 07:45 AM NPT Wed
jobs:
  sync:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 20
    permissions: read-all
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        include:
          - runner: "ubuntu-24.04-arm"
            r2_mirror: "/bin/aarch64-Linux"
            repo: "bincache"
            script: "https://raw.githubusercontent.com/pkgforge/metadata/refs/heads/main/r2/scripts/sync_r2_mirror.sh"

          - runner: "ubuntu-latest"
            r2_mirror: "/bin/x86_64-Linux"
            repo: "bincache"
            script: "https://raw.githubusercontent.com/pkgforge/metadata/refs/heads/main/r2/scripts/sync_r2_mirror.sh"

          - runner: "ubuntu-24.04-arm"
            r2_mirror: "/bin/aarch64-Linux"
            repo: "pkgcache"
            script: "https://raw.githubusercontent.com/pkgforge/metadata/refs/heads/main/r2/scripts/sync_r2_mirror.sh"
          
          - runner: "ubuntu-latest"
            r2_mirror: "/bin/x86_64-Linux"
            repo: "pkgcache"
            script: "https://raw.githubusercontent.com/pkgforge/metadata/refs/heads/main/r2/scripts/sync_r2_mirror.sh"

    steps:
      - name: Install Addons
        run: |
          #presets
          set +x ; set +e
          #-------------#
          export DEBIAN_FRONTEND="noninteractive"
          sudo apt update -y -qq
          sudo apt install 7zip b3sum bc coreutils curl dos2unix fdupes jq git git-lfs moreutils wget util-linux -y -qq
          sudo apt install 7zip b3sum bc coreutils curl dos2unix fdupes jq git git-lfs moreutils wget util-linux -y -qq
          #bash <(curl -qfsSL "https://raw.githubusercontent.com/pkgforge/devscripts/refs/heads/main/Linux/install_bins_curl.sh")
          sudo curl -qfsSL "https://bin.pkgforge.dev/$(uname -m)-$(uname -s)/7z" -o "/usr/bin/7z" &
          sudo curl -qfsSL "https://bin.pkgforge.dev/$(uname -m)-$(uname -s)/7z" -o "/usr/local/bin/7z" &
          sudo curl -qfsSL "https://bin.pkgforge.dev/$(uname -m)-$(uname -s)/aria2" -o "/usr/local/bin/aria2" &
          sudo curl -qfsSL "https://bin.pkgforge.dev/$(uname -m)-$(uname -s)/aria2" -o "/usr/local/bin/aria2c" &
          sudo curl -qfsSL "https://bin.pkgforge.dev/$(uname -m)-$(uname -s)/b3sum" -o "/usr/bin/b3sum" &
          sudo curl -qfsSL "https://bin.pkgforge.dev/$(uname -m)-$(uname -s)/b3sum" -o "/usr/local/bin/b3sum" &
          sudo curl -qfsSL "https://bin.pkgforge.dev/$(uname -m)-$(uname -s)/eget" -o "/usr/local/bin/eget" &
          sudo curl -qfsSL "https://bin.pkgforge.dev/$(uname -m)-$(uname -s)/jq" -o "/usr/local/bin/jq" &
          sudo curl -qfsSL "https://bin.pkgforge.dev/$(uname -m)-$(uname -s)/oras" -o "/usr/local/bin/oras" &
          sudo curl -qfsSL "https://bin.pkgforge.dev/$(uname -m)-$(uname -s)/ouch" -o "/usr/local/bin/ouch" &
          sudo curl -qfsSL "https://bin.pkgforge.dev/$(uname -m)-$(uname -s)/rclone" -o "/usr/local/bin/rclone" &
          sudo curl -qfsSL "https://bin.pkgforge.dev/$(uname -m)-$(uname -s)/rsync" -o "/usr/local/bin/rsync" &
          sudo curl -qfsSL "https://bin.pkgforge.dev/$(uname -m)-$(uname -s)/yq" -o "/usr/local/bin/yq" &
          wait ; echo
          sudo chmod -v 'a+x' \
           "/usr/bin/7z" \
           "/usr/local/bin/7z" \
           "/usr/local/bin/aria2c" \
           "/usr/bin/b3sum" \
           "/usr/local/bin/b3sum" \
           "/usr/local/bin/eget" \
           "/usr/local/bin/jq" \
           "/usr/local/bin/oras" \
           "/usr/local/bin/ouch" \
           "/usr/local/bin/rclone" \
           "/usr/local/bin/rsync" \
           "/usr/local/bin/yq"
        continue-on-error: true

      - name: Setup Env
        run: |
          #presets
          set +x ; set +e
          #-------------#
          ##tmp
          SYSTMP="$(dirname $(mktemp -u))" && export SYSTMP="${SYSTMP}"
          echo "SYSTMP=${SYSTMP}" >> "${GITHUB_ENV}"
          #-------------#
          ##Git
          sudo apt-get install git-lfs -y -qq
          echo "GH_PAGER=" >> "${GITHUB_ENV}"
          gh config set prompt disabled
          ##rClone
          mkdir -p "${HOME}/.config/rclone"
          echo "${{ secrets.R2_MIRROR_TOKEN }}" > "${HOME}/.config/rclone/rclone.conf"
          #-------------#
          ##User-Agent
          USER_AGENT="$(curl -qfsSL 'https://raw.githubusercontent.com/pkgforge/devscripts/refs/heads/main/Misc/User-Agents/ua_firefox_macos_latest.txt')" && export USER_AGENT="${USER_AGENT}"
          echo "USER_AGENT=${USER_AGENT}" >> "${GITHUB_ENV}"
        continue-on-error: true

      - name: Sync Mirror [${{ matrix.repo }} ==> ${{ matrix.hf }}]
        env:
          GHCR_TOKEN: "${{ github.token }}"
          GITHUB_TOKEN: "${{ github.token }}"
          R2_MIRROR: "${{ matrix.r2_mirror }}"
          UPSTREAM_REPO: "${{ matrix.repo }}"
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          curl -qfsSL "${{ matrix.script }}" -o "./sync.sh"
          dos2unix --quiet "./sync.sh"
          chmod +x "./sync.sh"
          PARALLEL_LIMIT="$(($(nproc)+1))" bash "./sync.sh"
          wait ; echo
        continue-on-error: true
